# Generated by Django 4.1.7 on 2023-03-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='battery',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='rom',
            field=models.CharField(max_length=100),
        ),
    ]
